set -g status-bg colour236 # bg color              
set -g status-fg white # fg color
set -g status-left " [#S] " # info
set -g status-right " #(whoami)@#h | %d.%m.%Y | %H:%M " # displays user@hostname, date, time

bind r source-file ~/.tmux.conf \; display "Config reloaded!"  

set -g base-index 1
setw -g pane-base-index 1

set -g history-limit 10000              
set -g status-interval 5 
